### ISSUE TITLE
add more items in the gitignore

### ISSUE THREAD

**Issue by Awinja-j** [kountable/Bot#1]
use https://www.gitignore.io/ to add more items to be ignored in your gitignore.
Please add
MacOS, 
Python, 
Virtualenv, 
Visual Studio(Or the IDE you use)

**Comment by Kwamboka82** [comment]
What's the purpose of adding the above in gitignore?

**Comment by Awinja-j** [comment]
@Kwamboka82 

https://stackoverflow.com/questions/13675216/why-should-i-use-gitignore
